### ISSUE TITLE
Option to show only active simulators in sidebar

### ISSUE THREAD

**Issue by AndreiVidrasco** [twostraws/ControlRoom#10]
In Xcode Project Navigator, besides filter field there are other small buttons, like to show files with git changes.
Maybe we can add such icon in this filter field, to show all active(booted) simulators?

Will require some designer help to come up with nice icon as well.

**Comment by twostraws** [comment]
Note for whoever takes a shot at this: tooltips don't exist in SwiftUI right now, but there are some hacks around that overlay an `NSView` to get a similar effect. Without a tooltip the button might be a bit inscrutable.
