### ISSUE TITLE
Unable to build Release scheme (CoreSimulator.framework missing arm64?)

### ISSUE THREAD

**Issue by james-rantmedia** [twostraws/ControlRoom#103]
I was unable to build ControlRoom in the Release scheme as Xcode says the CoreSimulator.framework is missing one or more architectures required by this target: arm64).

Debug scheme built without issues.

Xcode 12.4
macOS 11.1 (20C69)

**Comment by twostraws** [comment]
As far as I know this isn't something we can fix; just don't build in release mode 🤷‍♂️

**Comment by twostraws** [comment]
I've added a change that might help – it certainly works for me, but that doesn't mean it's a great long-term fix.

**Comment by dchakarov** [comment]
On M1 works via Rosetta
<img width="361" alt="image" src="https://user-images.githubusercontent.com/1482285/106209048-4be55a00-61bc-11eb-831f-fc7fa6c6e103.png">

**Comment by twostraws** [comment]
Thanks for checking!

**Comment by james-rantmedia** [comment]
Awesome :)

**Comment by pdxplaid** [comment]
Ha! that fixed it for me on my m1 mini. I didn't realize this option was there in Xcode. duh. I had already built it on my Intel mac and it works great, but I'm glad to have this option pointed out on the Apple Silicon. thanks!

**Comment by nashysolutions** [comment]
Hi @twostraws reading through this I can see that you guys have accepted a workaround by selecting the rosetta target, effectively simulating non-M1 macs. 

I have a working fix to make this project work on M1 macs. 
Please consider re-opening this ticket.

**Comment by twostraws** [comment]
@nashysolutions I'm always happy to receive PRs, with or without an open issue attached.
