### ISSUE TITLE
M1 Support?

### ISSUE THREAD

**Issue by hedlynogan** [twostraws/ControlRoom#118]
Hi Paul,
I am a huge fan and based on your review I went and bought a M1 Mac Mini. However, I guess you have not tried to build this on your M1 or you would notice it would fail with the following errors.

/Users/nedh/Develop/PaulHudson/ControlRoom/ControlRoom/Simulator UI/ControlScreens/LocationView.swift:41:17: error: cannot find 'Map' in scope
Map(coordinateRegion: $currentLocation, annotationItems: annotations) { location in
^~~
/Users/nedh/Develop/PaulHudson/ControlRoom/ControlRoom/Simulator UI/ControlScreens/LocationView.swift:42:21: error: cannot find 'MapPin' in scope
MapPin(coordinate: CLLocationCoordinate2D(latitude: location.latitude, longitude: location.longitude), tint: .red)

It builds without issues on my i9.
I am running Xcode 12.4 and Big Sur 11.3 Beta.

Any idea when you will support M1? I don't see any claim in the README?

**Comment by hedlynogan** [comment]
Paul said: "That's odd – I don't think that's an M1 issue. Others have reported it building just fine with M1."

I moved this to it's own issue and copied your response Paul. 

I tried removing and a fresh clone, toggling Mac | or Rosetta, remove deriviedData, doesn't make a difference, won't build on my M1, noticing other odd behavior in system preferences and app file dialogs hanging, caused real concern.

However, I took a async/await preview class and I forgot to uncheck the Swift Development Snapshot. My bad, sorry.

**Comment by nashysolutions** [comment]
Runs fine for me

See bottom of this ticket

https://github.com/twostraws/ControlRoom/issues/103

**Comment by nashysolutions** [comment]
https://twitter.com/vatsal_manot/status/1360530574897606656?s=20

**Comment by Harry-KNIGHT** [comment]
Works fine on my MacBook Air M1 and my MacBook M1 Pro.

I think this issue can be closed.

**Comment by twostraws** [comment]
Thank you!
