### ISSUE TITLE
[Feature Request] Add a possibility to change the font size

### ISSUE THREAD

**Issue by AlexanderAlbertPinestack** [twostraws/ControlRoom#133]
First of all I want to say thank you very much. The app helps me a lot in my daily life. Especially for testing e.g. the light dark mode it is much more comfortable than switching the mode via device settings.

One thing that would make it perfect for me is to change the font-size to see if everything is still visible on very big font sizes. 

Thanks a lot and greetings.

**Comment by Mcrich23** [comment]
Made this happen, just needs to get accepted.

**Comment by Mcrich23** [comment]
Can we please close this @twostraws?
