### ISSUE TITLE
Cannot change time in Xcode 13 beta

### ISSUE THREAD

**Issue by sebino420** [twostraws/ControlRoom#134]
There is some issue going on with the Xcode 13 beta. When I click on "Set to 9:41" or just change time in general it doesn't work. Also, some other features don't work like the entire Network section, changing battery percentage and state, and sending notification from the App section

**Comment by Gryzle** [comment]
I'm still having this issue with the latest version of **Xcode 14.1**. Any solution to fix this, since this doesn't seem to be a widespread issue? I'm attempting to change the time to 9:41 AM on iPad devices.

**Comment by FelixLisczyk** [comment]
I have the same issue with the iOS 16.1 simulator. You can work around it by creating an iOS 16.0 simulator in Xcode 14.1.

https://developer.apple.com/forums/thread/720610

**Comment by FelixLisczyk** [comment]
The underlying issue has finally been fixed with Xcode 15.3.
