### ISSUE TITLE
Device list images look odd if many are missing

### ISSUE THREAD

**Issue by twostraws** [twostraws/ControlRoom#14]
@stefanomondino posted a screenshot of the app running on his Mac, and it seems to be missing almost all the device pictures. If two or three were missing I'd say it's OK, but here many are missing and all the question marks looks strange to me.

![Control Room image with many missing icons.](https://user-images.githubusercontent.com/190200/74448337-b188eb00-4e72-11ea-95c6-1af525cc12e5.png)

**Comment by davedelong** [comment]
@stefanomondino I have a theory... If I push up a branch would you be willing to try it out and see if it solves this?

**Comment by stefanomondino** [comment]
@davedelong sure!

**Comment by gereons** [comment]
Just in case another data point is needed: I see the same thing on my box, only the "Default" entry has an image, all the others show question marks. Let me know if/when I can help debug.

**Comment by davedelong** [comment]
I just reproduced this on my laptop. Investigating...

**Comment by davedelong** [comment]
OK, I think this related to #11 . The returned JSON doesn't have the device type identifier, so it's falling back to `public.device`. `public.device` doesn't have an icon, so it's default to the question mark icon (#9).
