### ISSUE TITLE
Not work on Xcode 13

### ISSUE THREAD

**Issue by priore** [twostraws/ControlRoom#142]
Unfortunately doesn't work anymore on Mac with Big Sur 11.6.1 with Xcode 13.1 and iPhone Simulator iPhone 8 iOS 11.4 😭

but was a great and very useful project ❤️

**Comment by twostraws** [comment]
We're not able to do anything with an issue report this vague – you haven't said what the problem is, or provided any details. If you'd like to try adding these things then perhaps we can try addressing the problem, however no one else has reported issues with that setup.

**Comment by priore** [comment]
Hello,
that's right, with the iOS 11 simulator I couldn't change the light / dark mode, I couldn't send pushes, the simulator doesn't receive, I tried opening a url (deeplink) and that works. Instead everything works with iOS 15.

I will continue with iOS 15 since has no problems, you can delete this ticket or put with low priority.

Thanks, great project.
