### ISSUE TITLE
Simulator isn't visible on booting it from Control Room

### ISSUE THREAD

**Issue by naoey** [twostraws/ControlRoom#157]
Hello,

Recently I've been running into an issue with ControlRoom where clicking "Boot" on a simulator fires it up but the window isn't made visible and neither is it present in my dock. I can see the Simulator process running and consuming memory, just don't see it anywhere. It works normally when launching it by running an app in Xcode.

Running Xcode 13.4.1 atm. I'm not sure what other details would help troubleshoot this issue, but happy to help obtain whatever information is required.

**Comment by naoey** [comment]
This issue still exists in the https://github.com/twostraws/ControlRoom/commit/00e53ccdf1e90be2e16af39e9b0364d6e1836bc0 and Xcode 15. #161 had fixed this issue for me and I was using it this whole time but it seems the author gave up on it.

**Comment by marcelmendesfilho** [comment]
Opened PR to fix this: [https://github.com/twostraws/ControlRoom/pull/192]

**Comment by twostraws** [comment]
Thank you!
