### ISSUE TITLE
Dependency on SwiftLint 0.39.1

### ISSUE THREAD

**Issue by ehmjaysee** [twostraws/ControlRoom#16]
It should be noted there is a compiler dependency on swiftlint 0.39.1

If you have the prior version installed (0.39.0) you will get many compile errors like this one:

Type Name Violation: Type name should only contain alphanumeric characters: 'DataView_Previews' (type_name)

**Comment by twostraws** [comment]
That's odd – I have 0.38.2 and don't get the errors. Maybe it was a feature introduced in a specific version then toned down shortly after?

**Comment by ehmjaysee** [comment]
<finishes drinking coffee, puts on reading glasses>

Turns out I had 0.34.0 installed when I thought it said 0.39.0

**Comment by twostraws** [comment]
I see. Well, we could add a suggestion to folks that they should upgrade, but that release is ~7 months old now so I think we might be OK without it. Let me know what you think.
