### ISSUE TITLE
Most of the stuff is not working. What am I doing wrong?

### ISSUE THREAD

**Issue by vandres** [twostraws/ControlRoom#23]
This tool looks very promising and I hope I can get it to work. Lately I had to test our app behaviour when the user revoke permissions (like Notifcation and Location). It would have saved me plenty of time, where I had to go into the Simulator settings and revoke these manually and then switch back to the app.

Unfortunatly most of the features don't work for me. My setup is 

MacOS Catalina 10.15.3
Simulator iOS 12.4: not working at all
Simulator iOS 13.3:

- Light/Dark: not working
- App Permissions Revoke/Grant/Reset: not working
- Uninstall App: working
- Push: not working
- Battery: working
- Location: not tested
- Network: not working
   
 Just tell me which information you need and I will gladly send it

**Comment by stefanomondino** [comment]
Many features will work only with XCode 11.4, currently beta.
Check this out https://developer.apple.com/documentation/xcode_release_notes/xcode_11_4_beta_release_notes

**Comment by vandres** [comment]
Thanks, will try that.

**Comment by vandres** [comment]
Can confirm, now it is working as intended.
