### ISSUE TITLE
[FR] Make "Uninstall App" button be confirmable

### ISSUE THREAD

**Issue by vandres** [twostraws/ControlRoom#26]
While testing the Tool, I accidentally uninstalled the app twice. I would suggest to move the button away from "Send Push" or make it at least so, that it needs to be confirmed.

**Comment by zengpeici** [comment]
> While testing the Tool, I accidentally uninstalled the app twice. I would suggest to move the button away from "Send Push" or make it at least so, that it needs to be confirmed.

is it means that 'could not uninstall app'?

**Comment by vandres** [comment]
@zengpeici Uninstalling works - too good I would mean :D I think it would be a better usability to move the button away from the current location, because it can to easily be hit on accident. Or at least a confirmation ala "Really uninstall?" should come

**Comment by zengpeici** [comment]
@vandres  good suggestion.

**Comment by MarioIannotta** [comment]
@davedelong I moved the button in https://github.com/twostraws/ControlRoom/pull/30. Do we still want to add the confirmation alert?

**Comment by davedelong** [comment]
Yes, let's re-purpose this as making it a confirmable action

**Comment by davedelong** [comment]
Fixed by #39
