### ISSUE TITLE
Feature Request: Simulator Management

### ISSUE THREAD

**Issue by mergesort** [twostraws/ControlRoom#29]
Managing simulators in Xcode is unfortunately quite a pain. The biggest issue is that every version of Xcode, all of the simulators are reinstalled, and you can only remove them one by one. The less time-consuming (yet time-consuming) approach is usually to delete them all and add them back one by one.

It'd be great to have a way to do this through ControlRoom to batch up requests, rather than doing it one by one every few months.

Upon suggestion from @twostraws, one idea would be to add an Edit/Done button for the current sidebar to show a list of checkboxes, with a delete button in that context to formalize the action.

An alternative idea I'd propose would be to provide identifiers for the simulators you'd like to install.

Thanks a lot!

**Comment by twostraws** [comment]
How does that change work for you, Joe? You can select however many you want at once, right-click, then choose Delete.

**Comment by mergesort** [comment]
Just tired this out, amazing, it's everything I've ever wanted in Xcode. 😭

Paul, you truly are a king amongst us simple plebeians.
