### ISSUE TITLE
Feature "Always on top"

### ISSUE THREAD

**Issue by vomchik** [twostraws/ControlRoom#3]
Is it possible to add feature `always on top`?.
I remember this feature was in old ios simulator.

**Comment by twostraws** [comment]
This would be a great menu item, I think. I'll mark this as "Good First Issue" so someone can tackle it!

**Comment by paulofierro** [comment]
I believe this is now fixed by https://github.com/twostraws/ControlRoom/pull/15.

**Comment by twostraws** [comment]
Awesome – thank you!

**Comment by vomchik** [comment]
Awesome!!! Thanks a lot!!!
