### ISSUE TITLE
[FR] Rename a simulator

### ISSUE THREAD

**Issue by davedelong** [twostraws/ControlRoom#34]
Rename a simulator.

Not sure what the UX here would be. Maybe the giant name in the detail area can be editable?

**Comment by MarioIannotta** [comment]
On Xcode it is possible to rename simulators with the right click on the Sidebar (or selecting it and pressing the return key), maybe we could do the same here.

**Comment by davedelong** [comment]
Yeah, that's about the approach I'm taking
