### ISSUE TITLE
[FR] Clone a simulator

### ISSUE THREAD

**Issue by davedelong** [twostraws/ControlRoom#35]
This would be an easy thing to add in the contextual menu

`simctl clone [device id] [new name]`

**Comment by muukii** [comment]
Hi, thanks for the great development tool application.

This idea would be quite so helpful.
And Let me put my additional idea.

I'd like to get a function that can copy whole data on the simulator to the other device.
This would be helpful to check the UI behavior on the different screen sizes.

`whole data` means data directory.
![image](https://user-images.githubusercontent.com/1888355/74585441-0fa70100-5020-11ea-9839-374787a06bca.png)

**Comment by davedelong** [comment]
Currently working on this and #34 at the same time
<img width="643" alt="Screen Shot 2020-02-15 at 12 37 44 PM" src="https://user-images.githubusercontent.com/112699/74594124-1027a380-4ff0-11ea-878a-ec0a13662741.png">
<img width="1014" alt="Screen Shot 2020-02-15 at 12 37 50 PM" src="https://user-images.githubusercontent.com/112699/74594126-1289fd80-4ff0-11ea-8c7b-346761995c10.png">

**Comment by veb** [comment]
That looks perfect @davedelong 😄
