### ISSUE TITLE
Some ideas regarding push notifications

### ISSUE THREAD

**Issue by alladinian** [twostraws/ControlRoom#38]
Some ideas regarding push notifications:

1. Since the payload is specified, we could use fields that directly set values, so we could construct a JSON with, avoiding any syntax errors or typos in the payload
2. We could use two modes, one for the simplest notification (title, body) and an 'advanced' one that would support every possible type of payload. The benefit of this would be that in the first case we could have a much more intuitive way of creating simple test notifications by directly manipulating the information on a 'notification replica' view. I did some initial work and looks really nice imo (this is a working prototype where both title & body are directly editable)

<img width="590" alt="Screen Shot 2020-02-15 at 1 37 06 PM" src="https://user-images.githubusercontent.com/156458/74587193-48cb7b00-4ff8-11ea-8793-5a3043cde6c8.png">

I would appreciate any feedback, if you guys think that this is something worth exploring I would be more than willing to work on it.

**Comment by javb99** [comment]
I like the idea. It would be cool if you could switch between raw and specific fields.

**Comment by veb** [comment]
Sorta like how you store json in django - you have the option in admin to parse it or keep it raw.
