### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by veb** [twostraws/ControlRoom#40]
Is it possible that there's a way to make the simulator camera work, similar to how Android does?

**Comment by davedelong** [comment]
I've never come across a way to do this, unfortunately :(

**Comment by davedelong** [comment]
This would be really cool, but in all my searching on how to pull this off, I've not found anything that reliably works and doesn't involve insane amounts of injection and hacking. I think that's beyond the scope of this project, sorry.

If you find a way to do it, please let us know!
