### ISSUE TITLE
Be able to change simulator language

### ISSUE THREAD

**Issue by hansemannn** [twostraws/ControlRoom#48]
It would be great to be able to change simulator language via ControlRoom! If there is an underlaying command available already, I could take over the implementation!

**Comment by alladinian** [comment]
I was also wondering about that. Although I couldn't find a simctl command for setting a language or region, I _did_ find a nice article on [NSHipster ](https://nshipster.com/simctl/) that includes a possible solution for this (essentially you manipulate the  container's GlobalPreferences.plist file)

**Comment by davedelong** [comment]
Interesting... the path mentioned in the article is the `dataPath` value on `SimCtl.Device`...

**Comment by pluddy** [comment]
In progress on #59 🎉

**Comment by pluddy** [comment]
This was added in #59 🎉
