### ISSUE TITLE
[UI] use vector or Retina icons for Wi-Fi and cellular bars

### ISSUE THREAD

**Issue by ZevEisenberg** [twostraws/ControlRoom#54]
<img width="940" alt="image" src="https://user-images.githubusercontent.com/464574/74619126-77357d00-5102-11ea-8ef4-d27788868159.png">

I could try making them in Sketch, if you don't mind having a Sketch file checked into the repo, @twostraws.

**Comment by pluddy** [comment]
I tried to address this in #55 
let me know if those icons look off, I tried to just use some pdf exported SF Symbols

**Comment by davedelong** [comment]
Fixed in #55
