### ISSUE TITLE
App crashes when selecting the default simulator

### ISSUE THREAD

**Issue by dyang** [twostraws/ControlRoom#61]
Steps to reproduce:
- Make sure "Show default simulator" option is turned on in the preference
- Launch the app
- Select the very first simulator item from the sidebar, i.e. the one reads "Default"
- App crashes

It seems that the `selectedSimulators` property in `SimulatorsController` is unable to locate the selected simulator(s) when a simulator has "booted" as its udid.

**Comment by davedelong** [comment]
@dyang thank you for reporting this!

**Comment by dyang** [comment]
@davedelong Thanks for the quick fix!
