### ISSUE TITLE
A lot of previews are crashing

### ISSUE THREAD

**Issue by alladinian** [twostraws/ControlRoom#62]
I'm seeing a lot of previews crashing, mainly due to missing `environmentObject` injection (for example AppView is missing `UIState` and NetworkView is missing `Preferences` - this was pointed out by the crash logs at `~/Library/Logs/DiagnosticReports` and verified by manually adding the objects at the respective previews). 

I guess this is due to the assumption that injection happens at AppDelegate (?) and thus "inherited" (by silently launching the app) by every preview or this assumption should be valid and this is something that is failing due to my system setup (latest production version of Xcode)? Is anyone else having these problems?

**Comment by davedelong** [comment]
Interesting. I will investigate. Thanks for reporting!

**Comment by davedelong** [comment]
@alladinian Any chance you'd be willing to upload your crash logs? I've been trying to reproduce this but have been unable to.

Any other insights you have would be welcome as well.

**Comment by davedelong** [comment]
OH! This is about Xcode live previews, right?

**Comment by alladinian** [comment]
Oh yes 😋 sorry, I guess I could have made it  a little bit more clear in my message.
