### ISSUE TITLE
Icon should be a little smaller

### ISSUE THREAD

**Issue by AustinConlon** [twostraws/ControlRoom#69]
The icon sticks out as a little larger than other macOS apps with the circular format.
<img width="694" alt="Screen Shot 2020-03-01 at 1 03 16 AM" src="https://user-images.githubusercontent.com/1305957/75622853-9ea43500-5b59-11ea-85c5-16407871e703.png">

**Comment by twostraws** [comment]
Fixed in Control Room 2.0.
