### ISSUE TITLE
Odd overlaying issue

### ISSUE THREAD

**Issue by veb** [twostraws/ControlRoom#76]
I often get:

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/376245/76137508-d0118900-60a2-11ea-95f2-7b9bdf2b2455.png">

However if I click the system tab a few times it comes right again.

**Comment by twostraws** [comment]
Sadly this is a SwiftUI bug on macOS, and there isn't a lot we can do about it. I haven't had the problem since upgrading to macOS 10.15.4, but YMMV.
