### ISSUE TITLE
Ability to remove carrier

### ISSUE THREAD

**Issue by AustinConlon** [twostraws/ControlRoom#86]
One of Apple's [marketing and identity guidelines](https://developer.apple.com/app-store/marketing/guidelines/) is "Don’t show the name or identity of a carrier." Changing the Operator text field to blank does nothing, and it would be better if it instead removes the carrier text from the status bar. If you set it to be a space and then view it on say an iPhone 8 Plus, then there will be a space in the status bar.

**Comment by pluddy** [comment]
Is this still a bug?  Attempting to repro, but looks like setting 'Operator' to empty removes the text for me on both an iPhone 12 Pro Max and an iPhone 8 Plus.

![image](https://user-images.githubusercontent.com/8559597/106367023-670fb100-6305-11eb-97c6-79e77e6cddb8.png)
