### ISSUE TITLE
Overlapping views bug

### ISSUE THREAD

**Issue by grantat** [twostraws/ControlRoom#91]
I think I've found a small bug with the following steps:

1. Select Device Simulator (e.g. iPhone 11)
2. Select "App" tab
3. Click into the APS notification json/text block
4. Select a different tab (Where the bugs appear)

- You should notice that the selected tab isn't changed correctly on first select
- If you select another tab, not "App" or current tab selected, two views/settings pages will overlap.

Screenshot:
<img width="1069" alt="Screen Shot 2020-05-25 at 5 17 48 PM" src="https://user-images.githubusercontent.com/12538550/82843633-badf1600-9eab-11ea-8e5d-1647f7d2b1b8.png">

**Comment by twostraws** [comment]
Sadly this is a SwiftUI bug rather than something we can fix ourselves.
