### ISSUE TITLE
Record simulator video

### ISSUE THREAD

**Issue by Volker88** [twostraws/ControlRoom#94]
Is it possible to add the functionality to record a video from the simulator?

In the terminal it's possible to do it with the following command:

xcrun simctl io booted recordVideo <filename>.<file extension>

To stop the recording in terminal "cartel + c" needs to be clicked

**Comment by twostraws** [comment]
Hello! Yes, this is totally possible and it's been sitting in my to do list for a long time. Want to give it a try?

**Comment by Volker88** [comment]
I can give it  a try. But can't promise anything since I never worked with command line tools before.

I saw that some parts of screen recording are already implemented in the controller. I guess I just need to implement it to the user interface and need to figure out how to execute "ctrl + c" to stop the recording afterwards

**Comment by twostraws** [comment]
Yes: all the other requirements launch the xcrun process and terminate immediately, but this needs to run the process in the background and keep it active until we press Stop.

**Comment by Volker88** [comment]
I did now implement it now similar to the function for taking screenshots. but I receive an error when processing the command. 
Any idea how to troubleshoot it?
Also I couldn't find any information about how to terminate it when I press stop.

<img width="1049" alt="screen Recording" src="https://user-images.githubusercontent.com/47064750/86355673-557d0280-bc6b-11ea-9e16-467ecea34742.png">

**Comment by twostraws** [comment]
I'm not sure about that error because I haven't investigated it, but as I said you will need to run the process in the background and keep it active until we press Stop – this is different from our regular IO commands. Perhaps try to solve the problem in a new, simple macOS command line project so you can get it working without all the Control Room infrastructure?

**Comment by twostraws** [comment]
This was added in Control Room 2.0, just a couple of days before Xcode 12.5 added it natively 😂
